name: Check and Manage Notarization Submissions

on:
  workflow_dispatch:
    inputs:
      delete_id:
        description: "Optional submission ID to delete (leave blank to only show history)"
        required: false
        default: ""

jobs:
  manage-notarization:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show notarization submission history
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          echo "Fetching notarization submission history from Apple..."
          xcrun notarytool history \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID"

      - name: Delete specific notarization submission (optional)
        if: ${{ github.event.inputs.delete_id != '' }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          DELETE_ID: ${{ github.event.inputs.delete_id }}
        run: |
          echo "Attempting to delete submission ID: $DELETE_ID"
          xcrun notarytool log "$DELETE_ID" \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID"
          echo "Deleting submission..."
          xcrun notarytool remove "$DELETE_ID" \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID"
