name: Build & Release macOS App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*' # runs automatically when you push a version tag like v1.2.3

permissions:
  contents: write

jobs:
  build:
    name: Build, Sign, Notarize, and Release macOS App
    runs-on: macos-latest
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      # Import .p12 certificate directly (not base64)
      - name: Import Apple Developer Certificate (.p12)
        run: |
          echo "🔐 Importing Apple Developer Certificate..."
          security create-keychain -p "$RUNNER_TEMP" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "$RUNNER_TEMP" build.keychain
          security import .github/certs/certificate.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "${{ secrets.APPLE_DEVELOPER_CERT_PASSWORD }}" \
            -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k "$RUNNER_TEMP" build.keychain
        shell: bash

      - name: Build Tauri app (macOS)
        run: npm run tauri build

      - name: Notarize app
        id: notarize
        run: |
          echo "🔍 Searching for .dmg or .app..."
          FILE_PATH=$(find src-tauri/target/release/bundle/macos -name "*.dmg" -o -name "*.app" | head -n 1)
          echo "📦 Found file: $FILE_PATH"

          if [[ "$FILE_PATH" == *.app ]]; then
            echo "📦 Zipping .app for notarization..."
            ZIP_PATH="${FILE_PATH%.*}.zip"
            ditto -c -k --keepParent "$FILE_PATH" "$ZIP_PATH"
            FILE_PATH="$ZIP_PATH"
          fi

          echo "🚀 Submitting $FILE_PATH for notarization..."
          set +e
          OUTPUT=$(xcrun notarytool submit "$FILE_PATH" \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID" \
            --wait 2>&1)
          STATUS=$?
          echo "$OUTPUT"
          set -e

          # Extract submission ID if available
          SUBMISSION_ID=$(echo "$OUTPUT" | grep -Eo '[A-F0-9-]{36}' | head -n 1)
          echo "SUBMISSION_ID=$SUBMISSION_ID" >> $GITHUB_ENV

          if [ $STATUS -ne 0 ]; then
            echo "❌ Notarization failed. Fetching detailed log..."
            if [ -n "$SUBMISSION_ID" ]; then
              xcrun notarytool log "$SUBMISSION_ID" \
                --apple-id "$APPLE_ID" \
                --team-id "$APPLE_TEAM_ID" \
                --password "$APPLE_APP_SPECIFIC_PASSWORD" || true
            else
              echo "⚠️ No submission ID found; skipping log fetch."
            fi
            exit 1
          fi

          echo "✅ Notarization successful!"
          echo "📎 Stapling..."
          if [[ "$FILE_PATH" == *.zip ]]; then
            APP_BUNDLE="${FILE_PATH%.zip}.app"
            xcrun stapler staple "$APP_BUNDLE"
          else
            xcrun stapler staple "$FILE_PATH"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/target/release/bundle/macos/*.dmg
            src-tauri/target/release/bundle/macos/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
